(()=>{
const toggle=document.querySelector('.menu-button'),menu=document.querySelector('.mobile-menu');
function closeMenu(){toggle?.setAttribute('aria-expanded','false');toggle?.setAttribute('aria-label','Öppna menyn');if(menu)menu.hidden=true;document.body.classList.remove('menu-open')}
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Stäng menyn':'Öppna menyn');menu.hidden=!open;document.body.classList.toggle('menu-open',open)});
matchMedia('(min-width:901px)').addEventListener('change',e=>{if(e.matches)closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();if(e.key==='Tab'&&!menu?.hidden){const all=[toggle,...menu.querySelectorAll('a,button')],first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const works=JSON.parse(document.querySelector('#works-data')?.textContent||'[]'),dialog=document.querySelector('.gallery-dialog');let current=0,visible=works.map(w=>w.id);
function showWork(id){const work=works.find(w=>w.id===id);if(!work)return;current=visible.indexOf(id);if(current<0){visible=works.map(w=>w.id);current=visible.indexOf(id)}document.querySelector('#dialog-image').src='assets/'+work.image;document.querySelector('#dialog-image').alt=work.alt;document.querySelector('#dialog-title').textContent=work.title;document.querySelector('#dialog-category').textContent=work.category;document.querySelector('#dialog-description').textContent=work.text;document.querySelector('.dialog-count').textContent=(current+1)+' / '+visible.length;const a=dialog.querySelector('.btn');a.href='kontakt.html?intresse='+encodeURIComponent(work.category);if(!dialog.open)dialog.showModal()}
document.querySelectorAll('.work-open').forEach(b=>b.addEventListener('click',()=>{visible=[...document.querySelectorAll('.work:not([hidden]) .work-open')].map(x=>x.dataset.work);showWork(b.dataset.work)}));
function next(delta){showWork(visible[(current+delta+visible.length)%visible.length])}
document.querySelector('#prev-work')?.addEventListener('click',()=>next(-1));document.querySelector('#next-work')?.addEventListener('click',()=>next(1));dialog?.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog?.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();next(1)}if(e.key==='ArrowLeft'){e.preventDefault();next(-1)}});dialog?.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('.work').forEach(w=>{w.hidden=b.dataset.filter!=='all'&&w.dataset.category!==b.dataset.filter;if(!w.hidden){count++;w.classList.remove('waiting')}});document.querySelector('.gallery').classList.toggle('filtered',b.dataset.filter!=='all');document.querySelector('#filter-status').textContent=count+' arbeten visas'}));
const form=document.querySelector('#enquiry');if(form){const interest=new URLSearchParams(location.search).get('intresse'),field=document.querySelector('#subject');const labels={'Spegelfönster':'Spegelfönster','Möbler':'Möbler och inredning','Byggnadssnickeri':'Byggnadssnickeri'};if(labels[interest])field.value=labels[interest]}
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),text=`Hej Kenneth!\n\nJag är intresserad av: ${f.get('subject')}\n\n${f.get('message')}\n\nNamn: ${f.get('name')}\nE-post: ${f.get('email')}\nTelefon: ${f.get('phone')||'Ej angivet'}`;document.querySelector('#email-draft').href='mailto:kenneth.andersson@lindesnickarn.se?subject='+encodeURIComponent('Förfrågan: '+f.get('subject'))+'&body='+encodeURIComponent(text);document.querySelector('#copy-message').dataset.text=text;const result=document.querySelector('#form-result');result.hidden=false;result.focus()});
document.querySelector('#copy-message')?.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(e.currentTarget.dataset.text);document.querySelector('#copy-status').textContent='Texten är kopierad.'}catch{document.querySelector('#copy-status').textContent='Använd Öppna mejlprogram för att fortsätta med utkastet.'}});
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion:reduce)').matches){document.documentElement.classList.add('js');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('waiting');obs.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('waiting');obs.observe(e)})}
})();
